{% set name = "cardiac-geometries-core" %}
{% set python_min = "3.10" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cardiac_geometries_core-{{ version }}.tar.gz
  sha256: 2775230f070f6586706bd9a155ba47b7a13fc766d150a39000fee274568e3657

build:
  number: 0
  noarch: python
  entry_points:
    - "geo=cardiac_geometries_core.cli:app"
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - python-gmsh
    - rich-click

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pip
  imports:
    - cardiac_geometries_core
  source_files:
    - tests/
    - pyproject.toml
  commands:
    - geo --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests


about:
  home: https://github.com/ComputationalPhysiology/cardiac-geometries-core
  summary: Gmsh files for cardiac geometries
  license: MIT
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/cardiac-geometries-core
  dev_url: https://github.com/ComputationalPhysiology/cardiac-geometries-core

extra:
  recipe-maintainers:
    - finsberg
